### ISSUE TITLE
Can not taxi in grass

### ISSUE THREAD

**Issue by Harald67** [Harald67/c150#35]
The aircraft slows down a lot, and sometimes get stuck in the grass.
Check FDM friction of wheels perhaps.

**Comment by Harald67** [comment]
Same problem with the c172p, impossible to taxi correctly on grass. The c172p is not always stuck because of it's engine power but it will break sometimes.
Probably a too high rolling friction of the ground material.

**Comment by gilbertohasnofb** [comment]
I think the friction of the ground is defined in the xml files inside of `FGDATA/Materials`. Maybe we should ask for someone to review those values for the grass?

**Comment by Harald67** [comment]
I had a quick look in material and in the property tree ; I found a jsbsim property for ground but there was a value of 5 for the rolling friction, I could not find that value in Materials/*.
So this probably need to understand how that value is computed or add some nasal code to check the material name under the wheels to know what is the material that is 'bugged'.

**Comment by gilbertohasnofb** [comment]
If you are using ALS, check for instance `FGDATA/Materials/regions/global-summer.xml`. You will find a definition for the landclass `Grassland`, which has the following friction:

`<friction-factor>0.7</friction-factor>`

Note that there are more than one types of landclass for grass (I believe `GrasCover` and `Greenspace` are other ones), and it also depends on the region you are (since each of those xml files get activated in specific latitude x longitude values).
