### ISSUE TITLE
The battery should discharged faster when starting the engine

### ISSUE THREAD

**Issue by Harald67** [Harald67/c150#47]
split from #43

The starter is not modeled yet in the electrical circuit. The battery should discharge a lot faster as soon as the started is added.

**Comment by Harald67** [comment]
I've added a 100 Ampere starter.
But the electrical circuit code will not discharge the battery with that.

**Comment by ghost** [comment]
Why close this issue? As far as I understand battery still doesn't discharge faster..

**Comment by Harald67** [comment]
I think It is now a problem of modeling the battery behavior. The actual code is doing a linear computation of the charge percentage of the battery based on the current usage. This is perhaps not what happens in real life but I doubt we can find a better approximation.

With the 100 Ampere starter the battery discharges faster than before but probably not as fast as it should.

**Comment by gilbertohasnofb** [comment]
Yep, I can confirm that this issue has been fixed, the starter does discharge the battery faster. @D-ECHO are you sure you did a `git pull` and are on the `master` branch?

**Comment by ghost** [comment]
sry misunderstood what Harald wrote and am not near a computer ftm

---

Gesendet mit der Telekom Mail App
http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm

--- Original-Nachricht ---
Von: Gilberto Agostinho
Betreff: Re: [Harald67/c150] The battery should discharged faster when 
starting the engine (#47)
Datum: 18.08.2016, 15:58 Uhr
An: Harald67/c150
Cc: D-ECHO, Mention

Yep, I can confirm that this issue has been fixed, the starter does 
discharge the battery faster. @D-ECHO https://github.com/D-ECHO are you 
sure you did a git pull and are on the master branch?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/Harald67/c150/issues/47#issuecomment-240730992 , or 
mute the thread
