### ISSUE TITLE
Various animation bugs with wheels and gear struts

### ISSUE THREAD

**Issue by Harald67** [Harald67/c150#59]
- the wheels don't spin at the correct speed, they spin too fast
- the nose gear strut has an animation problem when turning left of right like if the axis was not aligned
- the upper and lower damper objects dont reach at the correct position
- the nose gear strut should be remodeled and textured (the chrome animation does not work anymore)

**Comment by gilbertohasnofb** [comment]
Would it also be possible to lower the contact point of the wheels and ground a bit so that the wheels do not "enter" the ground?:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/17783960/c852333a-657a-11e6-9ac7-e2104b612ea4.png)

**Comment by Harald67** [comment]
I think it's detailed enough now.
![image](https://cloud.githubusercontent.com/assets/6804046/18029070/53885dde-6c8e-11e6-99d7-f420502928a3.png)

**Comment by Harald67** [comment]
Texturing will be done later #48 #49

**Comment by ghost** [comment]
beautiful

---

Gesendet mit der Telekom Mail App
http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm

--- Original-Nachricht ---
Von: Harald JOHNSEN
Betreff: Re: [Harald67/c150] Various animation bugs with wheels and gear 
struts (#59)
Datum: 27.08.2016, 19:42 Uhr
An: Harald67/c150

I think it's detailed enough now.
[image]
https://cloud.githubusercontent.com/assets/6804046/18029070/53885dde-6c8e-11e6-99d7-f420502928a3.png

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/Harald67/c150/issues/59#issuecomment-242930628 , or 
mute the thread

**Comment by gilbertohasnofb** [comment]
Fantastic!
